### PR TITLE
Safe up downcast

### LINKED ISSUE #107: Support up/down cast
- upcasting is safe and should succeed.
- downcasting can fail, but should be safe.
  - try_ somthing naming is desired.

### PR DESCRIPTION
**Pull request by kenz-gelsoft**
Close  #107

* Safe upcasting
    * From trait impls to convert to ancestor classes (except mix-in classes)
* Safe downcasting
    * wxObject-derived classes impl DynamicCast trait which support dynamic cast with `as_unowned<wx::Class>`

### CODE REVIEW

File: wx-core/src/generated.rs [hunk 1]
```diff
@@ -488,6 +488,21 @@ impl<const OWNED: bool> ListBoxMethods for CheckListBoxIsOwned<OWNED> {
         }
     }
 }
+impl<const OWNED: bool> From<CheckListBoxIsOwned<OWNED>> for ListBoxIsOwned<OWNED> {
+    fn from(o: CheckListBoxIsOwned<OWNED>) -> Self {
+        unsafe { ListBoxIsOwned::from_ptr(o.as_ptr()) }
+    }
+}
+impl<const OWNED: bool> TryFrom<&ListBoxIsOwned<OWNED>> for CheckListBoxIsOwned<false> {
```
Comment (kenz-gelsoft) [inline wx-core/src/generated.rs:496]: Generic TryFrom can't be implemented because of conflict with blanket impl in core.

We need repeat this per MxN combination of Base x Derived.
